import './modules/header.js';
import './modules/hero.js';
import './modules/tours.js';
import './modules/training.js';
import './modules/about.js';
import './modules/reviews.js';
import './modules/advantages.js';
import './modules/gallery.js';
import './modules/validation.js';
